### ISSUE TITLE
Please do not use the spring configuration namespace

### ISSUE THREAD

**Issue by snicoll** [oembedler/graphql-spring-boot#1]
Hello,

As requested [in our documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming), please do not use the [`spring` namespace for your own configuration](https://github.com/oembedler/graphql-spring-boot/blob/master/graphql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphql/boot/GraphQLProperties.java#L30)

**Comment by oembedler** [comment]
@snicoll have no clue how that wast missed. [Commit](https://github.com/oembedler/graphql-spring-boot/commit/13026c50f312f421ea856ea9b085a5e0bd275236) should fix the issue. Thanks!
